services:
  previewer:
    build:
      context: ../
      dockerfile: build/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ../logs:/app/logs
      - ../storage:/app/storage
    restart: unless-stopped