run:
  tests: true

linters-settings:
  funlen:
    lines: 150
    statements: 80
  depguard:
    list-type: "allow"
    include-go-root: true
    packages:
      - "main"  # разрешённые пакеты
      - "std"    # стандартная библиотека
      - "github.com/IKolyas/*"
      - "github.com/davidbyttow/govips/v2/vips" 
      - "github.com/stretchr/testify/assert"

linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - dogsled
    - dupl
    - durationcheck
    - errorlint
    - exhaustive
    - funlen
    - gci
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - gofumpt
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - lll
    - makezero
    - misspell
    - nestif
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - tagliatelle
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - wastedassign
    - whitespace
    - copyloopvar